version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=medusashop_db
      - POSTGRES_USER=medusashop_user
      - POSTGRES_PASSWORD=medusashop_pass
    user: 1000:1000  # Используем unprivileged пользователя

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=medusashop_db
      - POSTGRES_USER=medusashop_user
      - POSTGRES_PASSWORD=medusashop_pass
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume: