# Generated by Django 5.1.3 on 2024-11-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsonwarehouse',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
