# Generated by Django 5.1.3 on 2024-11-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
