# Generated by Django 5.1.3 on 2024-11-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_user_date_joined_user_groups_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatinorder',
            name='quantity',
            field=models.PositiveIntegerField(default=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whatinorder',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
